# Generated by Django 4.2 on 2023-04-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_details',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('emp_id', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=10)),
                ('phone_no', models.IntegerField()),
                ('photo', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
