# Generated by Django 4.2 on 2023-04-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_emp_details_password_alter_emp_details_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_details',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
