# Generated by Django 4.2 on 2023-04-14 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0005_announcement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='announcement',
            new_name='announcements',
        ),
    ]
